### ISSUE TITLE
[BUG] mailu-admin and mailu-webmail CrashLoopBackOff due to Redis connection error (Errno -5)

### ISSUE THREAD

**Issue by kaizerpwn** [Mailu/helm-charts#373]
**Describe the bug**
The Mailu admin and webmail pods are crashing with a CrashLoopBackOff status. Logs indicate a Redis connection issue with the error Name has no usable address (Errno -5).

Steps to reproduce:
- Install Mailu on Kubernetes using MicroK8s and my values.yaml
- Check the status of the pods in the mail namespace.
- Observe mailu-admin and mailu-webmail in CrashLoopBackOff.
- Review the logs of the mailu-admin pod for Redis connection errors.

```
root@uspolodev:~# microk8s kubectl get pods -n mail
NAME                              READY   STATUS             RESTARTS      AGE
mailu-admin-6cc797dd56-zzgp7      0/1     CrashLoopBackOff   1 (13s ago)   42s
mailu-clamav-0                    0/1     Running            0             41s
mailu-dovecot-797cb79599-cwsbs    1/1     Running            0             41s
mailu-front-7b8c8dcd7b-xgdhz      1/1     Running            0             41s
mailu-oletools-75d8774797-l6k8g   1/1     Running            0             42s
mailu-postfix-6d67467c96-kcdnw    1/1     Running            0             42s
mailu-redis-master-0              1/1     Running            0             41s
mailu-rspamd-cdbb6d8f4-7dj94      0/1     Running            0             42s
mailu-tika-dfb4ddbc6-jrlcv        1/1     Running            0             41s
mailu-webmail-84f956bc45-jc5wh    0/1     CrashLoopBackOff   2 (13s ago)   42s

root@uspolodev:~# microk8s kubectl logs mailu-admin-6cc797dd56-zzgp7 -n mail
WARNING:root:Your CPU has Advanced Vector Extensions available, we recommend you enable hardened-malloc earlier in the boot process by adding LD_PRELOAD=/usr/lib/libhardened_malloc.so to your mailu.env
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/redis/connection.py", line 276, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/app/venv/lib/python3.12/site-packages/redis/connection.py", line 277, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/redis/connection.py", line 607, in _connect
    for res in socket.getaddrinfo(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 963, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -5] Name has no usable address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/venv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/app/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()
  File "/app/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 236, in run
    super().run()
  File "/app/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
    ^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/app/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/app/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/gunicorn/util.py", line 424, in import_app
    app = app(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "/app/mailu/__init__.py", line 117, in create_app
    return create_app_from_config(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mailu/__init__.py", line 48, in create_app_from_config
    utils.session.init_app(app)
  File "/app/mailu/utils.py", line 497, in init_app
    MailuSessionExtension.cleanup_sessions(app)
  File "/app/mailu/utils.py", line 436, in cleanup_sessions
    for key in app.session_store.list():
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mailu/utils.py", line 162, in list
    return list(self.redis.scan_iter(match=prefix))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/redis/commands/core.py", line 3051, in scan_iter
    cursor, data = self.scan(
                   ^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/redis/commands/core.py", line 3026, in scan
    return self.execute_command("SCAN", *pieces, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/redis/client.py", line 542, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/redis/connection.py", line 1109, in get_connection
    connection.connect()
  File "/app/venv/lib/python3.12/site-packages/redis/connection.py", line 282, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -5 connecting to mailu-redis-master.mail.svc.cluster.local:6379. Name has no usable address.
```

**Environment**
- Kubernetes: MicroK8s 
- My values.yaml: https://pastebin.com/r6sqksmN

**Additional context**
It seems the issue is with the DNS resolution for mailu-redis-master.mail.svc.cluster.local. It could be related to Kubernetes DNS, Redis service misconfiguration, or network issues.

**Comment by arslanakhtar61** [comment]
I am getting the same error. Where you able to resolve it?
